### ISSUE TITLE
Some files are not uploading

### ISSUE THREAD

**Issue by donmega** [Rambalac/ACDDokanNet#11]
Getting the following error:
```
CreateFile: \Howard Stern Radio Shows\2015\2015-04 April 24Ks final\2015-04-03 Scott Weiland & The Wildabouts.mp3
  Access:[ReadAttributes]
  Share:[ReadWrite, Delete]
  Mode:[Open]
  Options:[35651584]
  Attr:[0]

System.AggregateException: One or more errors occurred. ---> Azi.Tools.HttpWebException: The remote server returned an error: (400) Bad Request.
   at Azi.Tools.HttpClient.GeneralExceptionProcessor(Exception ex)
   at Azi.Tools.Retry.<Do>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Tools.HttpClient.<Send>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Tools.HttpClient.<Send>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Tools.HttpClient.<GetJsonAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Amazon.CloudDrive.AmazonNodes.<GetChild>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.ACDDokanNet.FSProvider.<FetchNode>d__53.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Azi.ACDDokanNet.VirtualDrive._CreateFile(String fileName, FileAccess access, FileShare share, FileMode mode, FileOptions options, FileAttributes attributes, DokanFileInfo info)
   at Azi.ACDDokanNet.VirtualDrive.CreateFile(String fileName, FileAccess access, FileShare share, FileMode mode, FileOptions options, FileAttributes attributes, DokanFileInfo info)
---> (Inner Exception #0) Azi.Tools.HttpWebException: The remote server returned an error: (400) Bad Request.
   at Azi.Tools.HttpClient.GeneralExceptionProcessor(Exception ex)
   at Azi.Tools.Retry.<Do>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Tools.HttpClient.<Send>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Tools.HttpClient.<Send>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Tools.HttpClient.<GetJsonAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Amazon.CloudDrive.AmazonNodes.<GetChild>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.ACDDokanNet.FSProvider.<FetchNode>d__53.MoveNext()<---

D:\dev2\amazon-clouddrive-dokan\amazon-clouddrive-dokan\VirtualDrive.cs: 105

**Comment by Rambalac** [comment]
Is it still an issue?
