### ISSUE TITLE
Browser login never pops up - [Remote server returned error: (400)]

### ISSUE THREAD

**Issue by beebowbow** [Rambalac/ACDDokanNet#35]
Log Name:      Application
Source:        ACDDokan.Net
Date:          10/26/2016 11:16:42 AM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      BeeBowBow
Description:
MountButton_Click: Azi.Tools.HttpWebException: The remote server returned an error: (400) Bad Request.
   at Azi.Tools.HttpClient.<GeneralExceptionProcessor>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Tools.Retry.<Do>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Tools.HttpClient.<SendForm>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Tools.HttpClient.<PostForm>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Amazon.CloudDrive.AmazonDrive.<UpdateToken>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Amazon.CloudDrive.AmazonDrive.<AuthenticationByTokens>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.ACDDokanNet.Gui.App.<Authenticate>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.ACDDokanNet.Gui.App.<>c__DisplayClass49_0.<<Mount>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.ACDDokanNet.Gui.App.<Mount>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.ACDDokanNet.Gui.ViewModel.<Mount>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.ACDDokanNet.Gui.MainWindow.<MountButton_Click>d__3.MoveNext()

H:\Projects\C#\ACDDokanNet\ACD.DokanNet.Gui\MainWindow.xaml.cs: 33
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ACDDokan.Net" />
    <EventID Qualifiers="0">0</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-10-26T18:16:42.000000000Z" />
    <EventRecordID>1063714</EventRecordID>
    <Channel>Application</Channel>
    <Computer>BeeBowBow</Computer>
    <Security />
  </System>
  <EventData>
    <Data>MountButton_Click: Azi.Tools.HttpWebException: The remote server returned an error: (400) Bad Request.
   at Azi.Tools.HttpClient.&lt;GeneralExceptionProcessor&gt;d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Tools.Retry.&lt;Do&gt;d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Tools.HttpClient.&lt;SendForm&gt;d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Tools.HttpClient.&lt;PostForm&gt;d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Amazon.CloudDrive.AmazonDrive.&lt;UpdateToken&gt;d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.Amazon.CloudDrive.AmazonDrive.&lt;AuthenticationByTokens&gt;d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.ACDDokanNet.Gui.App.&lt;Authenticate&gt;d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.ACDDokanNet.Gui.App.&lt;&gt;c__DisplayClass49_0.&lt;&lt;Mount&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.ACDDokanNet.Gui.App.&lt;Mount&gt;d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.ACDDokanNet.Gui.ViewModel.&lt;Mount&gt;d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azi.ACDDokanNet.Gui.MainWindow.&lt;MountButton_Click&gt;d__3.MoveNext()

H:\Projects\C#\ACDDokanNet\ACD.DokanNet.Gui\MainWindow.xaml.cs: 33</Data>
  </EventData>
</Event>

**Comment by beebowbow** [comment]
[ACDDokanNetLog.txt](https://github.com/Rambalac/ACDDokanNet/files/554167/ACDDokanNetLog.txt)

**Comment by Rambalac** [comment]
After mount fails do you get any message with "The remote server returned an error: (400) Bad Request."?

**Comment by beebowbow** [comment]
yes, as states in the title
