### ISSUE TITLE
StrongNamer.AddStrongName task failed unexpectedly

### ISSUE THREAD

**Issue by bhallaheemanshu** [Rambalac/ACDDokanNet#42]
I have downloaded solution. Unsigned the Assemblies,Provided Amazon Key and Secret Statically and build the solution and got error as below - 

StrongNamer.AddStrongName task failed unexpectedly.....

What could be possible solution to it ?

Please find below complete Details of errror

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "StrongNamer.AddStrongName" task failed unexpectedly.
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'DokanNet, Version=1.1.0.0, Culture=neutral, PublicKeyToken=cef3dedf553bda55'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.ModuleDefinition.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
   at Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypeDefs()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__1_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
   at StrongNamer.AddStrongName.ProcessAssembly(ITaskItem assemblyItem, StrongNameKeyPair key)
   at StrongNamer.AddStrongName.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Cloud.DokanNet.Gui

**Comment by Rambalac** [comment]
You need to resign each project with your personal sign in project properties.

**Comment by bhallaheemanshu** [comment]
@Rambalac  Can i run project without signin

**Comment by Rambalac** [comment]
You can run main app if remove signing and strong namer but Win Explorer extension cannot work without strong name.

**Comment by bhallaheemanshu** [comment]
main app means ? which one?

**Comment by Rambalac** [comment]
Gui

**Comment by bhallaheemanshu** [comment]
Do you mean Cloud.DokanNet.Gui ? 
But this is the only project that is having error

**Comment by bhallaheemanshu** [comment]
![image](https://cloud.githubusercontent.com/assets/7411405/20969210/fd4839ec-bcad-11e6-9a26-c5821ab9b3e5.png)

**Comment by bhallaheemanshu** [comment]
I got to fix that error but i a getting Please install dokan 1.0 now

**Comment by Rambalac** [comment]
So?

**Comment by bhallaheemanshu** [comment]
thanks for info I am currently dealing with authentication it could be good if you add more in document. But i think it is very helpful

**Comment by ariesmun** [comment]
hi Rambalac, 

at the top you said that "...Win Explorer extension cannot work without strong name".
May i know what won't work? any link which can give me some more info about this?

Thanks

**Comment by Rambalac** [comment]
Extension for Windows Explorer context menu.
