### ISSUE TITLE
Issues when uploading files other than .txt files

### ISSUE THREAD

**Issue by ariesmun** [Rambalac/ACDDokanNet#56]
Hi,

I always have issues whenever i uploaded non-txt file (like xlsx, docs, zip). 
It keeps looping and caching the files in the cache folder (more and more files are being created - same size, same content, just different names). Can give me some insights where is the code which does the copying/caching ?

I'm using OneDrive.

Thanks,

**Comment by andrei-cst** [comment]
Hello, I also experience this issue with version 1.6.4 under Windows 7 & Windows Server 2016, but not all the time. Sometimes it works correctly for any files, sometimes it does this loop-thing. I'm not sure if it's just an assessment error regarding the percentage that was actually transferred or it just does not upload. Usually when it did this I re-uploaded the files using the web interface.

I attached the Exported Log file for more info from the Windows Server 2016 machine.
Here are the latest 2 errors in the log:
```
FindFiles: System.AggregateException: One or more errors occurred. ---> System.TimeoutException: The operation has timed out.
   --- End of inner exception stack trace ---
   at Azi.Cloud.DokanNet.VirtualDrive.Wait[T](Task`1 task, Int32 timeout)
   at Azi.Cloud.DokanNet.VirtualDrive.FindFiles(String fileName, IList`1& files, DokanFileInfo info)
---> (Inner Exception #0) System.TimeoutException: The operation has timed out.<---


H:\Projects\C#\ACDDokanNet\amazon-clouddrive-dokan\VirtualDrive.cs: 215
```
```
FindFiles: System.AggregateException: One or more errors occurred. ---> System.TimeoutException: The operation has timed out.
   --- End of inner exception stack trace ---
   at Azi.Cloud.DokanNet.VirtualDrive.Wait[T](Task`1 task, Int32 timeout)
   at Azi.Cloud.DokanNet.VirtualDrive.FindFiles(String fileName, IList`1& files, DokanFileInfo info)
---> (Inner Exception #0) System.TimeoutException: The operation has timed out.<---


H:\Projects\C#\ACDDokanNet\amazon-clouddrive-dokan\VirtualDrive.cs: 215
```
Here is the full file:
https://we.tl/IPkbRCYGxV (available for 7 days)

And here is more information about this computer:
```
OS Name	Microsoft Windows Server 2016 Datacenter
Version	10.0.14393 Build 14393
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	EC2AMAZ-79CSCUJ
System Manufacturer	Xen
System Model	HVM domU
System Type	x64-based PC
System SKU	
Processor	Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz, 2400 Mhz, 1 Core(s), 1 Logical Processor(s)
BIOS Version/Date	Xen 4.2.amazon, 9 12 2016
SMBIOS Version	2.4
Embedded Controller Version	255.255
BIOS Mode	Legacy
Platform Role	Desktop
Secure Boot State	Unsupported
PCR7 Configuration	Not Available
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.14393.206"
User Name	Not Available
Time Zone	GTB Standard Time
Installed Physical Memory (RAM)	1.00 GB
Total Physical Memory	1.00 GB
Available Physical Memory	118 MB
Total Virtual Memory	2.81 GB
Available Virtual Memory	1.24 GB
Page File Space	1.81 GB
Page File	C:\pagefile.sys
Device Guard Virtualization based security	Not enabled
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	
```

**Comment by andrei-cst** [comment]
The files eventually did upload. It looks like it's simply a progress reporting problem.

Good work so far, can't wait to see what's up next :)

Andrei
