### ISSUE TITLE
Undefineable Timeouts  after a week runtime

### ISSUE THREAD

**Issue by totalisator** [Rambalac/ACDDokanNet#59]
After running a week without problems ACDDokanNet stopped working after i uploaded about 900gb and i can't get it to run anymore.
Internet connection is fine, but i recieve tons of timeout errors in the eventlog.
The amazon drive connection itself is fine because i can use it with other clients like netdrive.

These Errors keep pilling up in the Eventlog every 10+ some seconds:
> CreateFile:`` Timeout: \Amz_encFS\8TCwaTteia7l2BI,MhVQ21dr\1BkbKv2fZm81tWPh0oE1dMBG
>   Access:[ReadData, ReadExtendedAttributes, ReadAttributes, ReadPermissions, Synchronize]
>   Share:[None]
>   Mode:[Open]
>   Options:[None]
>   Attr:[Normal]
> 
> System.AggregateException: One or more errors occurred. ---> System.TimeoutException: The operation has timed out.
>    --- End of inner exception stack trace ---
>    at Azi.Cloud.DokanNet.VirtualDrive.Wait[T](Task`1 task, Int32 timeout)
>    at Azi.Cloud.DokanNet.VirtualDrive.CreateFile(String fileName, FileAccess access, FileShare share, FileMode mode, FileOptions options, FileAttributes attributes, DokanFileInfo info)
> ---> (Inner Exception #0) System.TimeoutException: The operation has timed out.<---
> 
> H:\Projects\C#\ACDDokanNet\amazon-clouddrive-dokan\VirtualDrive.cs: 126

> GetDiskFreeSpace: System.AggregateException: One or more errors occurred. ---> System.TimeoutException: The operation has timed out.
>    --- End of inner exception stack trace ---
>    at Azi.Cloud.DokanNet.VirtualDrive.Wait[T](Task`1 task, Int32 timeout)
>    at Azi.Cloud.DokanNet.VirtualDrive.GetDiskFreeSpace(Int64& freeBytesAvailable, Int64& totalNumberOfBytes, Int64& totalNumberOfFreeBytes, DokanFileInfo info)
> ---> (Inner Exception #0) System.TimeoutException: The operation has timed out.<---
> 
> H:\Projects\C#\ACDDokanNet\amazon-clouddrive-dokan\VirtualDrive.cs: 336

> CreateFile: Timeout: \Amz_encFS
>   Access:[Synchronize]
>   Share:[None]
>   Mode:[Open]
>   Options:[None]
>   Attr:[0]
> 
> System.AggregateException: One or more errors occurred. ---> System.TimeoutException: The operation has timed out.
>    --- End of inner exception stack trace ---
>    at Azi.Cloud.DokanNet.VirtualDrive.Wait[T](Task`1 task, Int32 timeout)
>    at Azi.Cloud.DokanNet.VirtualDrive.CreateFile(String fileName, FileAccess access, FileShare share, FileMode mode, FileOptions options, FileAttributes attributes, DokanFileInfo info)
> ---> (Inner Exception #0) System.TimeoutException: The operation has timed out.<---
> 
> H:\Projects\C#\ACDDokanNet\amazon-clouddrive-dokan\VirtualDrive.cs: 126

> FindFiles: System.AggregateException: One or more errors occurred. ---> System.TimeoutException: The operation has timed out.
>    --- End of inner exception stack trace ---
>    at Azi.Cloud.DokanNet.VirtualDrive.Wait[T](Task`1 task, Int32 timeout)
>    at Azi.Cloud.DokanNet.VirtualDrive.FindFiles(String fileName, IList`1& files, DokanFileInfo info)
> ---> (Inner Exception #0) System.TimeoutException: The operation has timed out.<---
> 
> H:\Projects\C#\ACDDokanNet\amazon-clouddrive-dokan\VirtualDrive.cs: 215

dunno what to do now.

**Comment by Rambalac** [comment]
Yes, I noticed it too, but hard to understand why. Probably I did something wrong in async code.

**Comment by Rambalac** [comment]
I looks Amazon now get timeouts almost constantly. While Explorer behavior is not correct I'm not sure how to fix. Probably return read error?
